apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources-configmap
  namespace: monitoring
  labels:
    name: grafana-datasources-configmap
data:
  datasource.yml: |-
    apiVersion: 1
    
    datasources:
      - name: prometheus
        type: prometheus
        access: proxy
        editable: true
        url: http://prometheus.monitoring.svc.cluster.local:9090
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboards-configmap
  namespace: monitoring
  labels:
    name: grafana-dashboards-configmap
data:
  dashboard.json: |-
    {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: monitoring
  labels:
    name: grafana
  name: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      name: grafana
  template:
    metadata:
      labels:
        name: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:latest
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 3000
            name: port3000
            protocol: TCP
        resources:
          limits:
            memory: 600Mi
            cpu: 600m
          requests:
            memory: 600Mi
            cpu: 600m
        volumeMounts:
          - name: grafana-datasources
            mountPath: /etc/grafana/provisioning/datasources
          - name: grafana-dashboards
            mountPath: /etc/grafana/provisioning/dashboards/
      volumes:
        - name: grafana-datasources
          configMap:
            defaultMode: 420
            name: grafana-datasources-configmap
        - name: grafana-dashboards
          configMap:
            defaultMode: 420
            name: grafana-dashboards-configmap
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  namespace: monitoring
  labels:
    name: grafana
  name: grafana
spec:
  ports:
    - name: "3000"
      port: 3000
      protocol: TCP
  selector:
    name: grafana