{
 "title": "Load Balancing Tests",
 "time": { "from": "2024-06-15T01:13:56.614Z", "to": "2024-06-15T01:31:31.896Z" },
 "templating": {
  "list": [
   {
    "name": "processors",
    "query": {
     "query": "label_values(container_memory_usage_bytes{container=~\"processor-.\"},container)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Request Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(request_count{pod=~\"$processors\"}[5m]))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Request Count by processor",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(request_count{pod=~\"$processors\"}[5m])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Count by status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(request_status[5m])) by (status)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Latency Percentile (seconds)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(full_request_latency_bucket[5m])) by (le))",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(full_request_latency_bucket[5m])) by (le))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.7, sum(rate(full_request_latency_bucket[5m])) by (le))",
     "legendFormat": "P70"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(full_request_latency_bucket[5m])) by (le))",
     "legendFormat": "P50"
    }
   ]
  },
  {
   "title": "P90 by processor (seconds)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(full_request_latency_bucket[5m])) by (le,routed_to))",
     "legendFormat": "P90 processor-{{routed_to}}"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "CPU Usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "(sum(rate(container_cpu_usage_seconds_total{container=~\"$processors\"}[1m])) by (container) / (sum(container_spec_cpu_quota{container=~\"$processors\"}) by (container) / sum(container_spec_cpu_period{container=~\"$processors\"}) by (container))) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU throttle",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "sum(irate(container_cpu_cfs_throttled_seconds_total{pod=~\"$processors\"}[5m])) by(pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage $processors (seconds)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 28 },
   "repeat": "processors",
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{container=~\"$processors\"}) by (container)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum (container_spec_memory_limit_bytes{container=~\"$processors\"}) by (container)",
     "legendFormat": "{{container}} limit "
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Memory Usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "(sum(container_memory_usage_bytes{container=~\"$processors\"}) by (container) / sum (container_spec_memory_limit_bytes{container=~\"$processors\"}) by (container)) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage (working_set) (%)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 37 },
   "targets": [
    {
     "expr": "(sum(container_memory_working_set_bytes{container=~\"processor-.\"}) by (container) / sum (container_spec_memory_limit_bytes{container=~\"processor-.\"}) by (container)) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage $processors (bytes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 46 },
   "repeat": "processors",
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{container=~\"$processors\"}) by (container)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum (container_spec_memory_limit_bytes{container=~\"$processors\"}) by (container)",
     "legendFormat": "{{container}} limit "
    }
   ]
  }
 ]
}