apiVersion: v1
kind: Pod
metadata:
  labels:
    app: http-processor-b
  name: processor-b
spec:
  containers:
  - name: processor-b
    image: processor:latest
    imagePullPolicy: "Never"
    resources:
      requests:
        memory: "32Mi"
        cpu: "100m"
      limits:
        memory: "32Mi"
        cpu: "100m"
    ports:
      - containerPort: 8083
        protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: processor-b
spec:
  selector:
    app: http-processor-b
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083