apiVersion: v1
kind: Pod
metadata:
  labels:
    app: http-processor-a
  name: processor-a
spec:
  volumes:
    - name: lt-results
      hostPath:
        path: /home/lucasdinnouti/Documents/loadtest_results
  containers:
  - name: processor-a
    image: processor:latest
    imagePullPolicy: "Never"
    resources:
      requests:
        memory: "128Mi"
        cpu: "500m"
      limits:
        memory: "128Mi"
        cpu: "500m"
    env:
      - name: INSTANCE_TYPE
        value: "a_large-cpu"
    volumeMounts:
      - name: lt-results
        mountPath: /loadtest_results
    ports:
      - containerPort: 8083
        protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: processor-a
spec:
  selector:
     app: http-processor-a
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083