apiVersion: v1
kind: Pod
metadata:
  labels:
    app: http-proxy
  name: proxy
spec:
  containers:
  - name: proxy
    image: proxy:2
    imagePullPolicy: "Never"
    resources:
      requests:
        memory: "256Mi"
        cpu: "500m"
      limits:
        memory: "256Mi"
        cpu: "500m"
    env:
      - name: ALGORITHM
        value: "machine_learning_weight"
      - name: WEIGHT_INTERVAL
        value: "5"
    ports:
      - containerPort: 8082
        protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: proxy
spec:
  selector:
    app: http-proxy
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082