apiVersion: v1
kind: Pod
metadata:
  labels:
    app: http-proxy
  name: proxy
spec:
  containers:
  - name: proxy
    image: proxy:latest
    imagePullPolicy: "Never"
    resources:
      requests:
        memory: "64Mi"
        cpu: "200m"
      limits:
        memory: "64Mi"
        cpu: "200m"
    env:
      - name: ALGORITHM
        value: "weighted_round_robin"
    ports:
      - containerPort: 8082
        protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: proxy
spec:
  selector:
    app: http-proxy
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082