apiVersion: v1
kind: Pod
metadata:
  labels:
    app: http-runner
  name: runner
spec:
  containers:
  - name: runner
    image: runner:latest
    imagePullPolicy: "Never"
    resources:
      requests:
        memory: "512Mi"
        cpu: "500m"
      limits:
        memory: "512Mi"
        cpu: "500m"
    env:
      - name: TIMEOUT
        value: "30"
    ports:
      - containerPort: 8081
        protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: runner
spec:
  selector:
    app: http-runner
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081