apiVersion: v1
kind: Pod
metadata:
  name: runner
spec:
  containers:
  - name: runner
    image: runner:latest
    imagePullPolicy: "Never"
    resources:
      requests:
        memory: "64Mi"
        cpu: "200m"
      limits:
        memory: "64Mi"
        cpu: "200m"

---
apiVersion: v1
kind: Service
metadata:
  name: runner
spec:
  selector:
    app.kubernetes.io/name: runner
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081