apiVersion: v1
kind: Pod
metadata:
  name: processor-a
spec:
  containers:
  - name: processor-a
    image: processor:latest
    imagePullPolicy: "Never"
    resources:
      requests:
        memory: "64Mi"
        cpu: "200m"
      limits:
        memory: "64Mi"
        cpu: "200m"

---
apiVersion: v1
kind: Service
metadata:
  name: processor-a
spec:
  selector:
    app.kubernetes.io/name: processor-a
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8083