apiVersion: v1
kind: Pod
metadata:
  name: proxy
spec:
  containers:
  - name: proxy
    image: proxy:latest
    imagePullPolicy: "Never"
    resources:
      requests:
        memory: "64Mi"
        cpu: "200m"
      limits:
        memory: "64Mi"
        cpu: "200m"

---
apiVersion: v1
kind: Service
metadata:
  name: proxy
spec:
  selector:
    app.kubernetes.io/name: proxy
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8082